Back-end ByteJam 2024/SandsofTime/Models/ErrorViewModel.cs
namespace SandsofTime.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Back-end ByteJam 2024/SandsofTime/Models/SandsOfTime.cs
namespace SandsofTime.Models;

public class SandsOfTime
{
    public Guid Id { get; set; }
    public string playerName { get; set; }
}

Back-end ByteJam 2024/SandsofTime/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SandsofTime.Models;

namespace SandsofTime.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Back-end ByteJam 2024/SandsofTime/Controllers/SandsOfTimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SandsofTime.Data;
using SandsofTime.Models;

namespace SandsofTime.Controllers
{
    public class SandsOfTimeController : Controller
    {
        private readonly SandsofTimeContext _context;

        public SandsOfTimeController(SandsofTimeContext context)
        {
            _context = context;
        }

        // GET: SandsOfTime
        public async Task<IActionResult> Index()
        {
            return View(await _context.SandsOfTime.ToListAsync());
            // return View();
        }


        public async Task<IActionResult> Name()
        {
            return View();
        }

        public async Task<IActionResult> Options()
        {
            return View();
        }
        

        // GET: SandsOfTime/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sandsOfTime = await _context.SandsOfTime
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sandsOfTime == null)
            {
                return NotFound();
            }

            return View(sandsOfTime);
        }

        // GET: SandsOfTime/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SandsOfTime/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,playerName")] SandsOfTime sandsOfTime)
        {
            if (ModelState.IsValid)
            {
                sandsOfTime.Id = Guid.NewGuid();
                _context.Add(sandsOfTime);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sandsOfTime);
        }

        // GET: SandsOfTime/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sandsOfTime = await _context.SandsOfTime.FindAsync(id);
            if (sandsOfTime == null)
            {
                return NotFound();
            }
            return View(sandsOfTime);
        }

        // POST: SandsOfTime/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,playerName")] SandsOfTime sandsOfTime)
        {
            if (id != sandsOfTime.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sandsOfTime);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SandsOfTimeExists(sandsOfTime.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sandsOfTime);
        }

        // GET: SandsOfTime/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sandsOfTime = await _context.SandsOfTime
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sandsOfTime == null)
            {
                return NotFound();
            }

            return View(sandsOfTime);
        }

        // POST: SandsOfTime/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var sandsOfTime = await _context.SandsOfTime.FindAsync(id);
            if (sandsOfTime != null)
            {
                _context.SandsOfTime.Remove(sandsOfTime);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SandsOfTimeExists(Guid id)
        {
            return _context.SandsOfTime.Any(e => e.Id == id);
        }
    }
}

Back-end ByteJam 2024/SandsofTime/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title Page</title>
    <link rel="stylesheet" href="~/css/title.css">
</head>

<div class="parallax layer" id="layer1"></div>
<div class="parallax layer" id="layer2">
    <h1>Not Very Visual Novel</h1>
    <br><div>
        <a asp-controller="SandsOfTime" asp-action="Name">
            <button name="Start">Start</button>
        </a>
    </div> <br>
    <div>
        <a asp-controller="SandsOfTime" asp-action="Options">
            <button name="Options">Options</button>
        </a>
    </div>
</div>
<div class="parallax layer" id="layer3"></div>
        
<script src="~/js/parallax.js"></script>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Create.cshtml
@model SandsofTime.Models.SandsOfTime

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SandsOfTime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="playerName" class="control-label"></label>
                <input asp-for="playerName" class="form-control" />
                <span asp-validation-for="playerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Delete.cshtml
@model SandsofTime.Models.SandsOfTime

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SandsOfTime</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.playerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.playerName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Details.cshtml
@model SandsofTime.Models.SandsOfTime

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SandsOfTime</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.playerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.playerName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Edit.cshtml
@model SandsofTime.Models.SandsOfTime

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SandsOfTime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="playerName" class="control-label"></label>
                <input asp-for="playerName" class="form-control" />
                <span asp-validation-for="playerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Index.cshtml
@model IEnumerable<SandsofTime.Models.SandsOfTime>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.playerName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        @* <tr> *@
        @*     <td> *@
        @*         @Html.DisplayFor(modelItem => item.playerName) *@
        @*     </td> *@
        @*     <td> *@
        @*         <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
        @*         <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
        @*         <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
        @*     </td> *@
        @* </tr> *@
}
    </tbody>
</table>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Name.cshtml
@model SandsOfTime

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>OnScreenKeyboard</title>
    <link rel="stylesheet" href="~/css/name.css">
</head>
<body>

    <h1>Enter Name</h1>
    <input type="text" id="textBar" required readonly>
    
    <!-- This button is used to create a new user name -->
    <button id="saveButton" onclick="saveName()">Create a new player name</button>

    <!-- Added a button to sign in and play if the user alreday played the game before.
     This will pull back all the saved settings in the database -->
    <button id="signIn">Sign in and Play</button>

    <div id="keyboard">
        <button type="button" value="1" onclick="input_Run(this.value);">1</button>
        <button type="button" value="2" onclick="input_Run(this.value);">2</button>
        <button type="button" value="3" onclick="input_Run(this.value);">3</button>
        <button type="button" value="4" onclick="input_Run(this.value);">4</button>
        <button type="button" value="5" onclick="input_Run(this.value);">5</button>
        <button type="button" value="6" onclick="input_Run(this.value);">6</button>
        <button type="button" value="7" onclick="input_Run(this.value);">7</button>
        <button type="button" value="8" onclick="input_Run(this.value);">8</button>
        <button type="button" value="9" onclick="input_Run(this.value);">9</button>
        <button type="button" value="0" onclick="input_Run(this.value);">0</button>

        <button type="button" value="q" onclick="input_Run(this.value);">q</button>
        <button type="button" value="w" onclick="input_Run(this.value);">w</button>
        <button type="button" value="e" onclick="input_Run(this.value);">e</button>
        <button type="button" value="r" onclick="input_Run(this.value);">r</button>
        <button type="button" value="t" onclick="input_Run(this.value);">t</button>
        <button type="button" value="y" onclick="input_Run(this.value);">y</button>
        <button type="button" value="u" onclick="input_Run(this.value);">u</button>
        <button type="button" value="i" onclick="input_Run(this.value);">i</button>
        <button type="button" value="o" onclick="input_Run(this.value);">o</button>
        <button type="button" value="p" onclick="input_Run(this.value);">p</button>

        <button type="button" value="a" onclick="input_Run(this.value);">a</button>
        <button type="button" value="s" onclick="input_Run(this.value);">s</button>
        <button type="button" value="d" onclick="input_Run(this.value);">d</button>
        <button type="button" value="f" onclick="input_Run(this.value);">f</button>
        <button type="button" value="g" onclick="input_Run(this.value);">g</button>
        <button type="button" value="h" onclick="input_Run(this.value);">h</button>
        <button type="button" value="j" onclick="input_Run(this.value);">j</button>
        <button type="button" value="k" onclick="input_Run(this.value);">k</button>
        <button type="button" value="l" onclick="input_Run(this.value);">l</button>

        <button type="button" value="z" onclick="input_Run(this.value);">z</button>
        <button type="button" value="x" onclick="input_Run(this.value);">x</button>
        <button type="button" value="c" onclick="input_Run(this.value);">c</button>
        <button type="button" value="v" onclick="input_Run(this.value);">v</button>
        <button type="button" value="b" onclick="input_Run(this.value);">b</button>
        <button type="button" value="n" onclick="input_Run(this.value);">n</button>
        <button type="button" value="m" onclick="input_Run(this.value);">m</button>
        
      
        <button type="button" class="space" value=" " onclick="input_Run(this.value);">Space</button>
        <button type="button" class="backspace" onclick="backspace();">Backspace</button>
        <button type="button" class="deleteName" onclick="deleteName();">Delete</button>
        
        
    </div>

    <script src="~/js/name.js"></script>

</body>
</html>

Back-end ByteJam 2024/SandsofTime/Views/SandsOfTime/Options.cshtml
@model SandsOfTime

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Options</title>
    <link rel="stylesheet" href="~/css/text-box.css">
</head>

<body>
<h1>Options</h1>
<a asp-controller="Home" asp-action="Index">
    <button value="Return to Title">Return to Title</button>
</a>
<form id="optionsForm" action="~/js/option.js">
    <fieldset>
        <legend>Text Box Color</legend>
        <input type="radio" id="Light" name="Box-Format" value="white">
        <label for="Light">Standard Light</label><br>
        <input type="radio" id="Dark" name="Box-Format" value="black">
        <label for="Dark">Standard Dark</label><br>
        <input type="radio" id="Mint" name="Box-Format" value="mint">
        <label for="Mint">Minty Fresh</label><br>
        <input type="radio" id="Tan" name="Box-Format" value="tan">
        <label for="Tan">Summer Tan</label><br>
        <input type="radio" id="Gray" name="Box-Format" value="gray">
        <label for="Gray">Metallic Gray</label>
    </fieldset>
    <br>

    <input type="checkbox" id="auto-type" value="True">
    <label for="auto-type">Type-Out Text</label><br><br>

    <input type="submit" value="Save Changes">
</form>
<div id="textbox">
    <p>This is an example textbox.</p>
</div>

<script src="~/js/option.js"></script>
    
</body>
</html>

Back-end ByteJam 2024/SandsofTime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SandsofTime</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SandsofTime.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SandsofTime</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SandsofTime - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>